on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Test with ansible-lint
        env:
          ANSIBLE_CONFIG: ./ansible.cfg
        run: |
          pip3 install ansible-lint
          ansible-lint
