on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: install dependencies
        run: pip3 install ansible ansible-lint

      - name: test with ansible-lint
        run: ansible-lint
        env:
          ANSIBLE_CONFIG: ./ansible.cfg
